## TODO: Make sure service running

- name: logstash_config | Create variable Indexer configuration
  template: 
    src=z-variable.conf.j2
    dest="{{logstash_etc_dir}}/z-variable.conf" 
    owner=root 
    group=root 
    mode=0644
  notify: 
    - validate conf  
    - restart supervisor
    - restart initd
  when: indexer_conf_var_install
  tags: 
   - logstash-server
   - logstash-conf

- name: logstash_config | Deploy template/file Indexer configuration
  template: 
    src="{{item.1.src}}"
    dest="{{logstash_etc_dir}}/{{item.0}}-{{item.1.name}}.conf" 
    owner=root
    group=root
    mode=0644
  notify: 
    - validate conf  
    - restart supervisor
    - restart initd
  with_indexed_items: indexer_conf
  when: indexer_conf_install
  tags: 
   - logstash-server
   - logstash-conf