## Stop suppport of 1.3
- name: logstash_install | Stop support for 1.3
  fail:
     msg="logstash 1.3 is not supported"
  when: logstash_version_major == "1.3"

- name: logstash_install | Delete config directory
  file: 
    path="{{logstash_etc_dir}}" 
    state="absent"
  when: logstash_clear_config

- name: logstash_install | Create Logstash directories
  file: 
    path="{{item}}" 
    owner=root 
    group=root 
    mode=0755 
    state=directory
  with_items:
   - "{{ logstash_install_dir }}"
   - "{{logstash_etc_dir}}"
   - "{{logstash_log_dir}}"
   - "{{logstash_extra_dir}}"
   - "{{ logstash_sources_dir }}"

- name: logstash_install | Fetch Logstash tar.gz
  get_url: 
    url={{ logstash_url }}-{{ logstash_version }}.tar.gz
    dest={{ logstash_sources_dir }}/logstash-{{ logstash_version }}.tar.gz
  register: logstash_tar

- name: logstash_install | untar Logstash tar.gz
  command: 
    tar zxf {{ logstash_sources_dir }}/logstash-{{ logstash_version }}.tar.gz -C {{ logstash_install_dir }} --strip 1
  when: logstash_tar | changed
  tags: logstash-server
  notify: 
    - validate conf  
    - restart supervisor
    - restart initd