---
- name: logstash_forward | Ensure logstash-forwarder has its config file
  template: 
    src=logstash_forwarder/logstash-forwarder.conf.j2
    dest={{logstash_forwarder_etc}}
    owner=root 
    group=root 
    mode=0755
  notify:
  - restart logstash-forwarder

- name: logstash_forward |  Copy logstash-forwarder deb file
  copy: 
    src=logstash-forwarder_0.3.1_amd64.deb 
    dest=/tmp/logstash-forwarder_0.3.1.deb

- name: logstash_forward |  Install logstash-forwarder
  shell: dpkg --skip-same-version -i /tmp/logstash-forwarder_0.3.1.deb
  register: dpkg_result
  changed_when:  '"Setting up" in dpkg_result.stdout'

- name: logstash_forward |  copy logstash-forwarder init file
  template:
    src=logstash_forwarder/logstash-forwarder.init
    dest=/etc/init.d/logstash-forwarder 
    owner=root 
    group=root 
    mode=755
  notify:
  - restart logstash-forwarder

- name: logstash_forward |  Ensure logstash-forwarder is up
  service: 
    name=logstash-forwarder 
    state=started