- name: start-stop | Create supervisor config for the logstash-server
  template: 
    src=supervisor_logstash_indexer.j2 
    dest="/etc/supervisor/conf.d/logstash_indexer.conf" 
    owner=root 
    group=root 
    mode=0644
  when: logstash_start_stop == "supervisor"
  tags: logstash-server

- name: start-stop | Create init.d script logstash-server
  template: 
    src=initd_logstash_index.j2
    dest="/etc/init.d/logstash" 
    owner=root 
    group=root 
    mode=0755
  when: logstash_start_stop == "initd"
  tags: deploy 

- name: start-stop | Start logstash-server
  service: 
    name=logstash 
    state=started 
    enabled=yes
  register: logstash_start
  when: logstash_start_stop == "initd" 