- name: start-stop | Create supervisor config for the logstash indexer
  template: 
    src=supervisor_logstash_indexer.j2 
    dest="/etc/supervisor/conf.d/logstash_indexer.conf" 
    owner=root 
    group=root 
    mode=0644
  notify:
   - restart service
  when: logstash_start_stop == "supervisor"

- name: start-stop | Create init.d script
  template: 
    src=initd_logstash_index.j2
    dest="/etc/init.d/logstash" 
    owner=root 
    group=root 
    mode=0755
  notify:
   - restart service
  when: logstash_start_stop == "initd"