- name: restart logstash-server
  assert: { that: True }
  changed_when: True
  notify:
    - validate conf
    - restart supervisor
    - restart initd

- name: validate conf
  command: "{{logstash_start_cmd}} --configtest"
  changed_when: False
  register: logstash_configtest
  failed_when: logstash_configtest.rc != 0

- name: restart supervisor
  service: 
    name=supervisor 
    state=restarted 
    enabled=yes
  when: logstash_start_stop == "supervisor"

- name: restart initd logstash-server
  service: 
    name=logstash 
    state=restarted 
    enabled=yes
  when: logstash_start_stop == "initd"

- name: restart kibana
  service: 
    name=kibana 
    state=restarted 
    enabled=yes
  when: logstash_start_stop == "initd"